package regen

import (
	"bytes"
	"fmt"
	"sort"
	"strings"

	"github.com/fdatoo/switchyard/internal/page"
)

// Render serializes a PageData to its canonical .layout.pkl representation.
// Output is deterministic: sections sorted by ID, props alphabetical.
func Render(p *page.PageData) ([]byte, error) {
	var buf bytes.Buffer
	w := &pklWriter{b: &buf}
	w.line(`import "switchyard:pages" as p`)
	w.line("")
	w.line("// Auto-generated by switchyardd regen — do not edit manually.")
	w.line("")
	w.line("sections: Listing<p.Section> = new {")
	sections := sortedSections(p.Sections)
	for _, s := range sections {
		renderSection(w, s, 1)
	}
	w.line("}")
	return buf.Bytes(), nil
}

func renderSection(w *pklWriter, s page.SectionData, depth int) {
	indent := strings.Repeat("  ", depth)
	className := sectionClassName(s.Type)
	w.raw(indent + "new " + className + " {\n")
	w.raw(fmt.Sprintf("%s  id = %q\n", indent, s.ID))
	if len(s.Props) > 0 {
		renderProps(w, s.Props, depth+1)
	}
	if len(s.Tiles) > 0 {
		w.raw(indent + "  tiles {\n")
		tiles := sortedTiles(s.Tiles)
		for _, t := range tiles {
			renderTile(w, t, depth+2)
		}
		w.raw(indent + "  }\n")
	}
	if len(s.Cells) > 0 {
		w.raw(indent + "  cells {\n")
		cells := sortedCells(s.Cells)
		for _, c := range cells {
			renderCell(w, c, depth+2)
		}
		w.raw(indent + "  }\n")
	}
	w.raw(indent + "}\n")
}

func renderTile(w *pklWriter, t page.TileData, depth int) {
	indent := strings.Repeat("  ", depth)
	className := tileClassName(t.Type)
	w.raw(indent + "new " + className + " {\n")
	w.raw(fmt.Sprintf("%s  id = %q\n", indent, t.ID))
	if len(t.Props) > 0 {
		renderProps(w, t.Props, depth+1)
	}
	w.raw(indent + "}\n")
}

func renderCell(w *pklWriter, c page.CellData, depth int) {
	indent := strings.Repeat("  ", depth)
	className := cellClassName(c.Type)
	w.raw(indent + "new " + className + " {\n")
	w.raw(fmt.Sprintf("%s  id = %q\n", indent, c.ID))
	if len(c.Props) > 0 {
		renderProps(w, c.Props, depth+1)
	}
	w.raw(indent + "}\n")
}

func renderProps(w *pklWriter, props map[string]any, depth int) {
	indent := strings.Repeat("  ", depth)
	keys := make([]string, 0, len(props))
	for k := range props {
		keys = append(keys, k)
	}
	sort.Strings(keys)
	for _, k := range keys {
		w.raw(fmt.Sprintf("%s%s = %s\n", indent, k, formatPklValue(props[k])))
	}
}

func sectionClassName(typ string) string {
	if strings.Contains(typ, "/") {
		return "p.Section" // third-party pack section
	}
	return "p." + typ + "Section"
}

func tileClassName(typ string) string {
	if strings.Contains(typ, "/") {
		return "p.Tile"
	}
	return "p." + typ + "Tile"
}

func cellClassName(typ string) string {
	if strings.Contains(typ, "/") {
		return "p.Cell"
	}
	return "p." + typ + "Cell"
}

func formatPklValue(v any) string {
	switch tv := v.(type) {
	case string:
		return fmt.Sprintf("%q", tv)
	case bool:
		if tv {
			return "true"
		}
		return "false"
	case float64:
		if tv == float64(int64(tv)) {
			return fmt.Sprintf("%d", int64(tv))
		}
		return fmt.Sprintf("%g", tv)
	case int, int32, int64:
		return fmt.Sprintf("%d", tv)
	case nil:
		return "null"
	default:
		return fmt.Sprintf("%q", fmt.Sprintf("%v", tv))
	}
}

func sortedSections(ss []page.SectionData) []page.SectionData {
	sorted := make([]page.SectionData, len(ss))
	copy(sorted, ss)
	sort.Slice(sorted, func(i, j int) bool { return sorted[i].ID < sorted[j].ID })
	return sorted
}

func sortedTiles(ts []page.TileData) []page.TileData {
	sorted := make([]page.TileData, len(ts))
	copy(sorted, ts)
	sort.Slice(sorted, func(i, j int) bool { return sorted[i].ID < sorted[j].ID })
	return sorted
}

func sortedCells(cs []page.CellData) []page.CellData {
	sorted := make([]page.CellData, len(cs))
	copy(sorted, cs)
	sort.Slice(sorted, func(i, j int) bool { return sorted[i].ID < sorted[j].ID })
	return sorted
}

type pklWriter struct{ b *bytes.Buffer }

func (w *pklWriter) line(s string) { w.b.WriteString(s + "\n") }
func (w *pklWriter) raw(s string)  { w.b.WriteString(s) }
