package regen

import (
	"bytes"
	"fmt"

	configpb "github.com/fdatoo/switchyard/gen/switchyard/config/v1"
)

// RenderArea serializes an AreaConfig to canonical .pkl. Deterministic.
// Emits a valid standalone Pkl module that amends switchyard:area, suitable
// for auto-discovery under <configDir>/areas/<id>.pkl.
func RenderArea(a *configpb.AreaConfig) ([]byte, error) {
	if a.GetId() == "" {
		return nil, fmt.Errorf("area: id required")
	}
	var buf bytes.Buffer
	w := &pklWriter{b: &buf}
	w.line(`amends "switchyard:area"`)
	w.line("")
	w.line("// Auto-generated by switchyardd regen — do not edit manually.")
	w.line("")
	w.line(fmt.Sprintf("id = %q", a.GetId()))
	w.line(fmt.Sprintf("displayName = %q", a.GetDisplayName()))
	if pid := a.GetParentId(); pid != "" {
		w.line(fmt.Sprintf("parentId = %q", pid))
	}
	return buf.Bytes(), nil
}
