package regen

import (
	"bytes"
	"fmt"

	configpb "github.com/fdatoo/switchyard/gen/switchyard/config/v1"
)

// RenderArea serializes an AreaConfig to canonical .pkl. Deterministic.
func RenderArea(a *configpb.AreaConfig) ([]byte, error) {
	if a.GetId() == "" {
		return nil, fmt.Errorf("area: id required")
	}
	var buf bytes.Buffer
	w := &pklWriter{b: &buf}
	w.line(`import "switchyard:areas" as ar`)
	w.line("")
	w.line("// Auto-generated by switchyardd regen — do not edit manually.")
	w.line("")
	w.line("new ar.Area {")
	w.line(fmt.Sprintf("  id = %q", a.GetId()))
	w.line(fmt.Sprintf("  displayName = %q", a.GetDisplayName()))
	if pid := a.GetParentId(); pid != "" {
		w.line(fmt.Sprintf("  parentId = %q", pid))
	}
	w.line("}")
	return buf.Bytes(), nil
}
