package regen

import (
	"bytes"
	"fmt"
	"sort"
)

// RenderEntityAreas serializes an entity-id → area-id mapping into the
// `entityAreas { ... }` Pkl block. Entries are emitted sorted by entity id
// for deterministic output.
func RenderEntityAreas(m map[string]string) ([]byte, error) {
	var buf bytes.Buffer
	w := &pklWriter{b: &buf}
	w.line("// Auto-generated by switchyardd regen — do not edit manually.")
	w.line("")
	w.line("entityAreas {")
	keys := make([]string, 0, len(m))
	for k := range m {
		keys = append(keys, k)
	}
	sort.Strings(keys)
	for _, k := range keys {
		w.line(fmt.Sprintf("  [%q] = %q", k, m[k]))
	}
	w.line("}")
	return buf.Bytes(), nil
}
