package regen

import (
	"bytes"
	"fmt"

	configpb "github.com/fdatoo/switchyard/gen/switchyard/config/v1"
)

// RenderScene serializes a SceneConfig to canonical .pkl. Reuses
// renderAction from regen.go since scene actions are the same ActionConfig
// shape automations use.
func RenderScene(s *configpb.SceneConfig) ([]byte, error) {
	if s.GetId() == "" {
		return nil, fmt.Errorf("scene: id required")
	}
	var buf bytes.Buffer
	w := &pklWriter{b: &buf}
	w.line(`import "switchyard:scenes" as sc`)
	w.line(`import "switchyard:automations" as auto`)
	w.line("")
	w.line("// Auto-generated by switchyardd regen — do not edit manually.")
	w.line("")
	w.line("new sc.Scene {")
	w.line(fmt.Sprintf("  id = %q", s.GetId()))
	w.line(fmt.Sprintf("  displayName = %q", s.GetDisplayName()))
	w.line("  actions {")
	for _, act := range s.GetActions() {
		renderAction(w, act, 2)
	}
	w.line("  }")
	w.line("}")
	return buf.Bytes(), nil
}
