/**
 * pkl-serialiser.ts — client-side mini-serialiser that reproduces the server-side
 * regen output (internal/page/regen/regen.go) for the live Pkl preview pane.
 *
 * Rules (must match server regen.go):
 *  - Props sorted alphabetically
 *  - String values quoted
 *  - Boolean values unquoted (true / false)
 *  - Numeric values: integers without decimal; floats with %g-like formatting
 *  - null → "null"
 *  - Sections sorted by ID; tiles/cells sorted by ID
 */

import type { SectionDef, TileDef, CellDef } from "../model";

function formatPklValue(v: unknown): string {
  if (v === null || v === undefined) return "null";
  if (typeof v === "boolean") return v ? "true" : "false";
  if (typeof v === "number") {
    return Number.isInteger(v) ? String(v) : v.toPrecision(6).replace(/\.?0+$/, "");
  }
  if (typeof v === "string") return JSON.stringify(v);
  return JSON.stringify(String(v));
}

function renderProps(props: Record<string, unknown>, indent: string): string {
  const keys = Object.keys(props).sort();
  return keys.map((k) => `${indent}${k} = ${formatPklValue(props[k])}`).join("\n");
}

function sectionClassName(type: string): string {
  return type.includes("/") ? "p.Section" : `p.${type}Section`;
}

function tileClassName(type: string): string {
  return type.includes("/") ? "p.Tile" : `p.${type}Tile`;
}

function cellClassName(type: string): string {
  return type.includes("/") ? "p.Cell" : `p.${type}Cell`;
}

function renderTile(t: TileDef): string {
  const lines = [`    new ${tileClassName(t.type)} {`, `      id = ${JSON.stringify(t.id)}`];
  if (t.props && Object.keys(t.props).length > 0) {
    lines.push(renderProps(t.props, "      "));
  }
  lines.push("    }");
  return lines.join("\n");
}

function renderCell(c: CellDef): string {
  const lines = [`    new ${cellClassName(c.type)} {`, `      id = ${JSON.stringify(c.id)}`];
  if (c.props && Object.keys(c.props).length > 0) {
    lines.push(renderProps(c.props, "      "));
  }
  lines.push("    }");
  return lines.join("\n");
}

function renderSection(s: SectionDef): string {
  const lines = [`  new ${sectionClassName(s.type)} {`, `    id = ${JSON.stringify(s.id)}`];
  if (s.props && Object.keys(s.props).length > 0) {
    lines.push(renderProps(s.props, "    "));
  }
  if (s.tiles && s.tiles.length > 0) {
    const sorted = [...s.tiles].sort((a, b) => a.id.localeCompare(b.id));
    lines.push("  tiles {", ...sorted.map(renderTile), "  }");
  }
  if (s.cells && s.cells.length > 0) {
    const sorted = [...s.cells].sort((a, b) => a.id.localeCompare(b.id));
    lines.push("  cells {", ...sorted.map(renderCell), "  }");
  }
  lines.push("  }");
  return lines.join("\n");
}

/**
 * Serialises a single section to its Pkl layout block.
 * Used by the live preview pane in the settings rail.
 */
export function serialiseSection(s: SectionDef): string {
  return renderSection(s);
}

/**
 * Serialises an array of sections to a full .layout.pkl file body.
 */
export function serialisePage(sections: SectionDef[]): string {
  const sorted = [...sections].sort((a, b) => a.id.localeCompare(b.id));
  return [
    `import "switchyard:pages" as p`,
    ``,
    `// Auto-generated by switchyardd regen — do not edit manually.`,
    ``,
    `sections: Listing<p.Section> = new {`,
    ...sorted.map(renderSection),
    `}`,
  ].join("\n");
}
